### ISSUE TITLE
White Background when opening Pictures

### ISSUE THREAD

**Issue by florian03-1** [EaranMaleasi/VB-Paradise-dark-theme#11]
Sorry for this bad english :)

When you open a picture there is a white box.
And also when the picture is open, there is a white border around the picture.

![image](https://user-images.githubusercontent.com/36850836/65822290-c6593f00-e241-11e9-9183-cdcb385cc9db.png)

When you can fix this bug, I will be happy, because I like your dark style very much 👍 

-Florian

**Comment by EaranMaleasi** [comment]
Just checked it, and found the white box.
![image](https://app.gitkraken.com/api/glo/boards/5d8b64048928e5000f678591/attachments/5d8fcd461693ef000f74c945)

Will be fixed by tomorrow, with some other stuff :D

**Comment by EaranMaleasi** [comment]
@flori2212 Just commited the fix, make sure to check for an update within Stylus. Sadly I didn't have the time for much else.
